project:
  type: website

website:
  description: "Nate Housley dot com"
  site-url: https://natehousley.com 
  title: "Nate Housley"
  navbar:
    right:
      - about.qmd
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    linestretch: 1.7



