project:
  type: website
  output-dir: docs

website:
  description: "Nate Housley dot com"
  site-url: https://natehousley.com 
  title: "Nate Housley"
  navbar:
    left:
      - about.qmd
format:
  html:
    theme:
      light: customlight.scss
      dark: customdark.scss
    css: styles.css
    linestretch: 1.7



