---
layout: post
title: On Water and AI
categories: 
    - water
date: "07/22/2025"
---

If you've arrived at this post with no knowledge of Matt Yglesias, your best course of action is to refrain from reading the link below and to close this tab. Go get a lemonade instead.

Yglesias on his [Substack](https://www.slowboring.com/p/theres-plenty-of-water-for-data-centers) takes a big swing on a hot issue in a very short post. It is not just unconvincing to those who know a bit about water. It is a dishonest and/or lazy post that threatens to become ammunition in the controversy over generative so-called AI resource usage, because of Yglesias's influence and because of how he hitches the issue to the buzzy topic of "abundance."

Let's jump in and look at the core of the argument. The concern over water comes from the fact that data centers, including the ones that AI companies have been building at a steady clip, consume water in order to cool their server racks. But for Yglesias, according to the title, "There's plenty of water for data centers." The subtitle reads, "Probably the last worry you should have about either water or AI." He bolsters this position with the idea that there is one weird trick that should further reassure us. 

"Energy is the real bottleneck for everything," reads the heading of the concluding section. The reasoning is that water is actually abundant, but most of it is simply seawater. We could remedy this through reverse osmosis desalination and have as much water as we want, if only we had enough energy. Yglesias proposes that solar farms replace cropland to provide the necessary energy for scale desalination at scale. (So he's also slipped us the solution to any and all water allocation problems, which should be bigger news?) And while Yglesias is a bit of a critic of the "abundance agenda" articulated by Ezra Klein and Derek Thompson, his diagnosis of why we don't have more solar will be familiar to those who have dipped their toe in that discourse. "Of course, as always, there are regulatory roadblocks," he writes. A man with a hammer has found a nail.

For someone who studies water or even lives in the arid Western US, the decisive pivot to energy is breathtaking. He writes, "Virtually all environmental issues converge on energy in the long run, and in principle, water scarcity can be overcome through more abundant energy." His concluding sentence reads, "Water scarcity issues can be managed, while the availability of energy is a much more pressing constraint." The way he breezes right past the difficulty of managing water scarcity really underscores his admission at the top of the post: "I haven't spent a lot of time thinking about water use or water scarcity." In fact, the prospect of managing [overpromised Colorado River](https://www.azcentral.com/story/news/local/arizona-environment/2025/07/21/states-face-crunch-time-to-fix-a-colorado-river-on-brink-of-failure/82718164007/) water currently has the US West at the brink of a full implosion. 

Yglesias doesn't appear to have spent a lot of time googling the issue either. A 2023 CNBC [article](https://www.cnbc.com/2023/01/27/why-desalination-wont-save-states-dependent-on-colorado-river-water.html) titled "Why desalination won't save states dependent on Colorado River water" lays out the drawbacks to the technology. Energy is one reason, so I guess the solar farms can take care of that. But then there's the cost and the pollution. One study of desalination of brackish groundwater in Texas showed a range of $357 to $782 per acre-foot -- which is a screaming deal. For saltier seawater, the cost is closer to $2,725. The byproduct is a concentrated brine that can contain toxins, and every gallon of fresh water produces about a gallon and a half of it. Desalination is currently part of [Colorado River negotiations](https://www.sltrib.com/news/environment/2024/12/07/utah-could-pay-california/) as a way to ease some of the contentious demands between the Upper and Lower Basins, but it is not currently being used to produce significant amounts of water despite the technology having been around for a while. The country's largest desalination plant, the Yuma Desalting Plant near the Mexican border, has only been operated on two occasions. (It's purpose is to deliver reasonably fresh water to Mexico according to the Colorado River Compact, something that the US is not all that concerned about.) All this is to say that the reverse osmosis technology that Yglesias touts in comparison to the older thermal desalination method is really of no account. 

The cost is a big sticking point. Why would someone pay $2,725 for an acre-foot of water when irrigators currently pay just for the costs of delivery, somewhere in the neighborhood of $20 to $40 per acre-foot? We very quickly find ourselves with a political and economic problem, as opposed to the technological one that Yglesias has dreamt up.

Energy is also needed for more than just desalination. As Yglesias mentions in his post without any further comment, "The United States has a lot of water, but a somewhat limited capacity to transport that water to arid regions." (He then posts a graph of renewable freshwater resources per capita that has no connection to any of the text anywhere in the post.) A couple of notable projects use enormous amounts of energy to move water to where it is desired. California's State Water Project includes the highest vertical lift of water in the world to deliver water to southern California. This is accomplished through the Edmonston Pumping Plant, which consumes 787 MW of electricity. The Central Arizona Project is the largest single electricity user in Arizona, as it uses 285 MW to pump water from the Colorado River Basin to the Phoenix-Tucson metro area. These are just vertical lifts, with much of the rest of the work being done by gravity. An [oddball suggestion](https://news.byu.edu/intellect/study-reveals-cost-energy-needed-to-pump-pacific-ocean-water-into-great-salt-lake) to pipe seawater to Great Salt Lake would require 400 MW of electricity, which would cost over $300 million annually. And the amount of water would only be about a third of what is needed to fill the lake to a healthy level.

Entirely absent from Yglesias's post is an acknowledgment that part of the strain on water resources from datacenters comes from energy production itself. Fossil fuel or nuclear power plants boil water to produce steam to turn turbines, and additional water is used to cool equipment. He makes no mention of the possibility of using solar power to provide power for datacenters directly. Let's give him an ounce of credit and assume that he wouldn't suggest using solar farms to desalinate water with which to supply coal power plants. But in case you are curious, solar and wind are intermittent power sources that are not generally suitable for the round-the-clock operation of datacenters. This is why the rapid growth of datacenters has prompted [headlines](https://www.technologyreview.com/2025/05/20/1116272/ai-natural-gas-data-centers-energy-power-plants/) like "AI could keep us dependent on natural gas for decades to come," according to the MIT Technology Review. 

I hope that at this point you're having doubts about the one weird trick. That's good, because if you ever talk to someone knowledgeable about water, you hopefully won't say something as goofy as "energy is the real bottleneck for everything." But is AI water consumption as really as bad as they say?

Yglesias questions the reporting on the topic by doing a clever read of a New York Times story about a Meta datacenter not far from Atlanta, Georgia. The headline reads, "Their Water Taps Ran Dry When Meta Built Next Door." This is notable in part because Georgia is not known as a water stressed state. Yglesias points out, however, that the couple at the center of the story complained about sediment from the construction of the datacenter and its impact on the family's well -- not necessarily the water consumption of the facility. "Importantly, though, this doesn't seem to have any relationship to the question of guzzling up water," Yglesias concludes. 

But the story also quotes the executive director of the Newton County Water and Sewerage Authority: "What the data centers don't understand is that they're taking up the community wealth. We just don't have the water." The story reports that the "data center uses about 10 percent of the county's total water use daily." The head of the water authority also reports that nine companies applied to build data centers there, "some asking for as much as six million gallons of water a day -- more than the county's entire daily use." Yglesias does not comment on this. Using the family's well as a hook for the story is a bit strange in this light, but data centers do appear to pose a threat to Newton County's water supplies. (One significant aspect to this is that data centers mostly use treated water from municipal and industrial systems. Untreated water can contain sediment or cause buildup or bacterial growth in cooling systems. And while household use generates much "greywater" and sewage that can theoretically be captured and reused, most of the water that goes through data centers gets evaporated. By the way, another source of concern with data centers is the rise in temperature for the water that does get released back to natural channels, since warmer water can disrupt riparian habitats.)

If data centers are causing headaches for Newton County, Georgia, you can bet that data centers in the West are worsening an already volatile situation. Yglesias doesn't refer to any of this reporting. His only example is the family in Georgia. But: "[Bloomberg News](https://www.bloomberg.com/graphics/2025-ai-impacts-data-centers-water-data/) found that about two-thirds of new data centers built or in development since 2022 are in places already gripped by high levels of water stress." Many of these sites are in the West, since land is cheap and cooling is more efficient due to the region's dry air and cool, desert nights. 

Yglesias doesn't mention this, but I will say, for consistency, that Biden's CHIPS Act provided for a slew of new semiconductor fabrication plants, many of which would be built in the West. The fate of the CHIPS Act is up in the air with the new Trump regime, but we should also be concerned about the potential water consumption of these semiconductor fabs, which would be significant.

The last remaining piece of Yglesias's argument rests on the small consumption of water for individual AI chatbot messages relative to other uses. "The true water-guzzler in the American economy, though, isn't data centers or electricity generation. It's agriculture." That's true. Yglesias seems to use this to suggest that water concerns are generally overblown: "Across the country, people are using water every day for things that have nothing to do with sustaining human life," and, "I think the bottom line remains that water is not generally scarce and that coming up with new economically useful things to do with water is good." I think it's outrageous to handwave water concerns as climate change [dries up rivers](https://e360.yale.edu/features/europe-rivers-drought) across Europe, for instance, but the point about the relative water consumption about chatbots is noted -- though the charts he includes don't report on AI photo or video generation. Oh well. I don't personally find a lot of value in the individual consumer footprint analysis for things like this anyway. 

I believe I've established why I think that the operation of data centers and the manufacture of semiconductors and server racks can have an outsize impact depending on where they take place. The West, for at least the last three years, has urgently, frantically been trying to do two things: transfer water out of the agricultural sector (without provoking a backlash from farmers) and reduce overall water consumption (due to a dwindling supply as a result of climate change). As data centers move into the region, they provide jobs and revenue, which means people come to depend on them. This puts additional consequence, in an already tense situation, on those two objectives. Yes, agriculture uses much more water. That's been a topic of conversation here since the 1970s, and there is simply no easy solution. If it was desalination, it would have been taken care of by now.

Also, imagine you're in an overloaded elevator having a conversation about whether someone needs to get off so you can all use the elevator safely. Someone new approaches and tries to get on the elevator. That person has now introduced another dimension to the conversation that no one wants, and I think most people would simply tell them to go away. I don't think that's far off from the current AI water/power situation, especially since in this analogy the person has eight fingers on each hand and looks bizarrely smooth. 

So is there plenty of water for data centers? I don't think you can answer the question very well without asking whose water and where. I would hesitate to issue a final judgment until we get [more data](https://www.npr.org/2025/05/07/1249592906/energy-water-ai-climate-tech) out of secretive tech companies. And I would also point out that with the growth rate of these companies and their data centers, the overall impact on water supplies could prove to be extremely significant. A [report](https://www.technologyreview.com/2025/05/20/1116327/ai-energy-usage-climate-footprint-big-tech/) estimates that the share of electricity going to data centers in the US may triple from 2024 to 2028, to as high as 580 TWh, driven largely by AI. Personally I'm more concerned about greenhouse gas production, but energy generation will also drive increased water consumption. There will always be some technology that gets touted that is supposed to mitigate these impacts -- such as [data centers](https://www.sltrib.com/news/environment/2022/07/11/yes-data-centers-use-lot-water/) that don't cool with water! -- but at the same time there will be a cheaper alternative. Guess which option is preferable to AI companies. 
